Sonder_Blu/urls.py
from django.contrib import admin
from django.urls import reverse_lazy
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from tv.views import HomeView, search, like, send_request, accept_request, cancel_request, remove_friend, profile, \
    GroupFormView, GroupCreateView, GroupDetailView, join_group, leave_group, delete_group, FeedbackCreateView, \
    ReviewCreateView, search_movies, search_people, add_favorite, CategoryFilterView, ReviewUpdateView, user_edit, \
    UpdateFormView, SearchView, FilmView, ProfileView, GroupView
from chat.views import IndexView
from multichat.views import multichat_view
from feed.views import feed_view, PostCreateView, CommentCreateView, post_like, AnswerCreateView, comment_like, \
    MessageCreateView, open_message
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import login
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic.base import RedirectView, TemplateView
from tv.regbackend import MyRegistrationView
from registration.backends.default.views import ActivationView, RegistrationView, ResendActivationView


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^search_view/$', SearchView.as_view(), name='search_view'),
    url(r'^film_view/$', FilmView.as_view(), name='film_view'),
    url(r'^profile_view/$', ProfileView.as_view(), name='profile_view'),
    url(r'^group_view/$', GroupView.as_view(), name='group_view'),

    url(r'^search/$', search, name='search'),
    url(r'^like/$', like, name='like'),
    url(r'^send_request/(?P<user_id>\d+)/$', send_request, name='send_request'),
    url(r'^accept_request/(?P<user_id>\d+)/$', accept_request, name='accept_request'),
    url(r'^cancel_request/(?P<user_id>\d+)/$', cancel_request, name='cancel_request'),
    url(r'^remove_friend/(?P<user_id>\d+)/$', remove_friend, name='remove_friend'),
    url(r'^group_form/$', GroupFormView.as_view(), name='group_form'),
    url(r'^group_create/$', GroupCreateView.as_view(), name='group_create'),
    url(r'^group/(?P<pk>\d+)/$', GroupDetailView.as_view(), name='group'),
    url(r'^join_group/(?P<group_id>\d+)/$', join_group, name='join_group'),
    url(r'^leave_group/(?P<group_id>\d+)/$', leave_group, name='leave_group'),
    url(r'^delete_group/(?P<group_id>\d+)/$', delete_group, name='delete_group'),
    url(r'^feedback_create/$', FeedbackCreateView.as_view(), name='feedback_create'),
    url(r'^review_create/(?P<movie_id>\d+)/$', ReviewCreateView.as_view(), name='review_create'),
    url(r'^search_movies/(?P<query>.+)/$', search_movies, name='search_movies'),
    url(r'^search_people/(?P<query>.+)/$', search_people, name='search_people'),
    url(r'^add_favorite/(?P<movie_id>\d+)/$', add_favorite, name='add_favorite'),
    url(r'^category_search/$', CategoryFilterView.as_view(), name='category_search'),
    url(r'^review_update/(?P<pk>\d+)/$', ReviewUpdateView.as_view(), name='review_update'),
    url(r'^user_update/$', user_edit, name='user_update'),
    url(r'^update_form/$', UpdateFormView.as_view(), name='update_form'),

                  url(r'^login/$',
                      auth_views.LoginView.as_view(
                          template_name='registration/login.html'),
                      name='auth_login'),
                  url(r'^logout/$',
                      auth_views.LogoutView.as_view(
                          template_name='registration/logout.html'),
                      name='auth_logout'),
                  url(r'^accounts/register/$',
                      MyRegistrationView.as_view(),
                      name='registration_register'),
                  url(r'^accounts/profile/(?P<user_id>\d+)/$', profile, name='profile'),

                  url(r'^password/change/$',
                      auth_views.PasswordChangeView.as_view(
                          success_url=reverse_lazy('auth_password_change_done')),
                      name='auth_password_change'),
                  url(r'^password/change/done/$',
                      auth_views.PasswordChangeDoneView.as_view(),
                      name='auth_password_change_done'),
                  url(r'^password/reset/$',
                      auth_views.PasswordResetView.as_view(
                          success_url=reverse_lazy('auth_password_reset_done')),
                      name='auth_password_reset'),
                  url(r'^password/reset/complete/$',
                      auth_views.PasswordResetCompleteView.as_view(),
                      name='auth_password_reset_complete'),
                  url(r'^password/reset/done/$',
                      auth_views.PasswordResetDoneView.as_view(),
                      name='auth_password_reset_done'),
                  url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
                      auth_views.PasswordResetConfirmView.as_view(
                          success_url=reverse_lazy('auth_password_reset_complete')),
                      name='password_reset_confirm'),

                  url(r'^activate/complete/$',
                      TemplateView.as_view(template_name='registration/activation_complete.html'),
                      name='registration_activation_complete'),
                  url(r'^activate/resend/$',
                      ResendActivationView.as_view(),
                      name='registration_resend_activation'),
                  # Activation keys get matched by \w+ instead of the more specific
                  # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
                  # that way it can return a sensible "invalid key" message instead of a
                  # confusing 404.
                  url(r'^activate/(?P<activation_key>\w+)/$',
                      ActivationView.as_view(),
                      name='registration_activate'),
                  url(r'^register/complete/$',
                      TemplateView.as_view(template_name='registration/registration_complete.html'),
                      name='registration_complete'),
                  url(r'^register/closed/$',
                      TemplateView.as_view(template_name='registration/registration_closed.html'),
                      name='registration_disallowed'),


    url(r'^accounts/', include('registration.backends.default.urls', namespace='accounts')),

    url(r'^chat/$', IndexView.as_view(), name='chat'),

    url(r'^multichat/$', multichat_view, name='multichat'),

    url(r'^feed/$', feed_view, name='feed'),
    url(r'^create_post/$', PostCreateView.as_view(), name='create_post'),
    url(r'^create_comment/(?P<post_id>\d+)/$', CommentCreateView.as_view(), name='create_comment'),
    url(r'^create_answer/(?P<comment_id>\d+)/$', AnswerCreateView.as_view(), name='create_answer'),
    url(r'^feed/post_like/$', post_like, name='post_like'),
    url(r'^feed/comment_like/$', comment_like, name='comment_like'),
    url(r'^message_create/(?P<user_id>\d+)/$', MessageCreateView.as_view(), name='message_create'),
    url(r'^open_message/(?P<message_id>\d+)/$', open_message, name='open_message'),

    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/base.old.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sonder Blu - {% block meta_title %}{% endblock meta_title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bootstrap/3.3.0/css/bootstrap.min.css">
    <link rel="stylesheet" href={% static "tv/css/main.css" %}>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-default">
        <h4 class="navbar-text"><a href="{% url 'home' %}">Sonder Blu</a></h4>
        <ul class="nav navbar-nav">
            <form style="margin-top: 10px" action="{% url 'search' %}">
                <input name="query" style="width: 200px" required>
                <input type="submit" class="button" value="Search">
            </form>
        </ul>
        <ul class="nav navbar-nav pull-right">
            {% if user.is_authenticated %}
                <li><a href="{% url "feed" %}">Feed</a></li>
                <li><a href="{% url "profile" request.user.pk %}">{{ request.user.username }}</a></li>
                <li>{{ unread_requests|length }}</li>
                <li><a href="{% url "accounts:auth_logout" %}">Logout</a></li>
            {% else %}
                <li><a href="{% url "accounts:auth_login" %}">Login</a></li>
                <li><a href="{% url "accounts:registration_register" %}">Register</a></li>
            {% endif %}
        </ul>
    </nav>

    {% block content %}
        <div class="row">
            <div class="col-md-8">
            <a href="{% url "category_search" %}" class="btn btn-default">Search by category</a>
                {% if query %}
                    <h4>You search for: {{ query }}</h4>
                    <p><a href="{% url "search_movies" query %}">Movies</a> <a href="{% url "search_people" query %}">People</a></p>
                {% endif %}
                {% if movies %}
                    <h2>Movies</h2>
                    {% for movie in movies %}
                        <h4>{{ movie.name }}</h4>
                        <p>Rating: {{ movie.rating }}</p>
                        <p>Category:
                            {% for category in movie.category.all %}
                                <a href="#">{{ category }}</a>
                            {% endfor %}
                        </p>
                        <video id="videoPrincipal" src="{{ movie.movie_file.url }}" controls preload width='75%' height='60%' currentTime="5">

                        </video>
                        <p>
                            <a href="{% url 'like' %}" data-id="{{ movie.id }}"
                              class="btn btn-primary like">Likes: {{ movie.total_likes }}</a>

                        <button class="btn btn-primary room-link" data-room-id={{ movie.room.id }}>Chat</button>
                        <div id="chats">
                        </div>
                            {% if movie not in request.user.profile.favorites.all %}
                            <a href="{% url "add_favorite" movie.pk %}" class="btn btn-primary">Add to favorites</a>
                            {% endif %}

                        <p style="text-align: justify; width: 75%">{{ movie.description }}</p>

                        {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}" style="color: red" {% endif %}>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                        <hr>
                        {% for review in movie.reviews_set.all %}
                            <p>{{ review.user }}</p>
                            <p>{{ review.review }}</p>
                            <p><video src="{{ review.video.url }}" controls width='50%' height='40%'></video></p>
                            <a href="{% url "review_update" review.pk %}" class="btn btn-primary">Edit</a>
                            <hr>
                            {% endfor %}



                        {% if not query %}
                        <form action="{% url "review_create" movie.pk %}" method="post" enctype="multipart/form-data"
                            style="margin-bottom: 50px">
                            {% csrf_token %}
                            {{ review_form.as_p }}
                            <input type="submit" value="Save"/>
                        </form>
                        {% endif %}

                        <hr>
                    {% endfor %}
                {% else %}
                    <h2>No items to display</h2>
                {% endif %}

            {% if not query %}
            <h4>Please, leave your feedback about platform:</h4>
            <form action="{% url "feedback_create" %}" method="post" enctype="multipart/form-data"
                  style="margin-bottom: 50px">
                {% csrf_token %}
                {{ feedback_form.as_p }}
                <input type="submit" value="Save"/>
            </form>
            <h4>Reviews</h4>
            {% for feedback in feedbacks %}
                <p>Author: {{ feedback.user.username }}</p>
                <p style="text-align: justify; width: 75%">{{ feedback.feedback }}</p>
                {% if feedback.video %}
                    <video src="{{ feedback.video.url }}" controls width='50%' height='40%'></video>
                {% endif %}
                <hr>
            {% endfor %}
            {% endif %}

            {% if people %}
            <h4>People</h4>
            {% for user in people %}
            <p><a href="{% url "profile" user.id %}">{{ user.username }}</a></p>
            {% endfor %}
            {% endif %}

            </div>
            <div class="col-md-4" style="text-align: right">
                {% if user.is_authenticated %}
                    <h4>Friends <span style="font-weight: lighter">{{ friends|length }}</span></h4>
                    <ul style="list-style-type: none">
                        {% for user in friends %}
                            <li style="margin-left: -40px; margin-bottom: 10px">
                                <a href="{% url "profile" user.pk %}">{{ user.username }}</a>
                            </li>
                        {% endfor %}
                    </ul>

                    <h4>Users</h4>
                    <ul style="list-style-type: none">
                        {% for user in users %}
                            {% if user in friends or user == request.user or user.username == 'admin' %}
                            {% else %}
                                <li style="margin-left: -40px; margin-bottom: 10px">
                                    <a href="{% url "profile" user.id %}">{{ user.username }}</a>
                                    {% if not user in sent_requests %}
                                        <a href="{% url 'send_request' user.id %}" class="btn btn-primary">Send friend
                                            request</a>
                                    {% else %}
                                        <button class="btn btn-primary disabled">Friend request sent</button>
                                    {% endif %}
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>

                    <h4>Groups</h4>
                    <ul style="list-style-type: none">
                        {% for group in groups %}
                            <li style="margin-left: -40px; margin-bottom: 10px">
                                <a href="{% url "group" group.pk %}">{{ group.name }} ({{ group.movie }})</a>
                            </li>
                        {% endfor %}
                    </ul>

                    <a href="{% url "group_form" %}" class="btn btn-default" style="margin-top: 20px">Create group</a>
{#                    <p><a href="{% url "chat" %}" class="btn btn-default" style="margin-top: 20px">Chat</a></p>#}
{#                    <p><a href="{% url "multichat" %}" class="btn btn-default" style="margin-top: 20px">Multichat</a></p>#}

                {% endif %}
            </div>
        </div>

</div>

    {% endblock content %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="{% static "tv/js/main.js" %}" type="text/javascript"></script>

{#<script type="text/javascript">#}
{#myVid = document.getElementById('videoPrincipal');#}
{#myVid.play();#}
{#myVid.currentTime ='{{ timediff }}';#}
{#</script>#}

{% block extra_scripts %}
<script type="text/javascript" src='{% static "multichat/js/multichat.js" %}'></script>
<script type="text/javascript" src='{% static "multichat/js/reconnecting-websocket.min.js" %}'></script>
{% endblock %}

</body>
</html>